### ISSUE TITLE
Add YouTube and Discord Icons to Front Page

### ISSUE THREAD

**Issue by ljeasson** [ljeasson/Oxonian-Games-Website#14]
Include this link for YouTube: [https://www.youtube.com/channel/UCVUeoh2aYy7qBcIEUQQfsGw](https://www.youtube.com/channel/UCVUeoh2aYy7qBcIEUQQfsGw)

Leave Discord link blank for now

**Comment by soumildatta** [comment]
Youtube button added, and discord button added and commented out since there is no link associated with it yet.
