### ISSUE TITLE
Tile Menu on Game Page

### ISSUE THREAD

**Issue by ljeasson** [ljeasson/Oxonian-Games-Website#3]
**Feature Request:**  Game page needs a responsive, tile-based game menu that provides links to the landing pages of the game

[Build a Responsive, Modern Dashboard Layout With CSS Grid and Flexbox](https://medium.com/better-programming/build-a-responsive-modern-dashboard-layout-with-css-grid-and-flexbox-bd343776a97e)

**Current Status:** Odd Infinitum has its own tile with a link to the landing page 

**Needed:**  
- Centering of tile grid (3x3)
- Tile animations
- Game title positioned underneath title

**Comment by soumildatta** [comment]
<img width="1680" alt="Screen Shot 2020-01-07 at 11 32 52 AM" src="https://user-images.githubusercontent.com/35431692/71915500-827bad00-3141-11ea-8022-ac86e8eccb1c.png">
**Grid**: Bootstrap small (col-sm) grid added. 
**Animations**: Tile zooms in when hovered over and zooms out (but not to original size) when clicked.

**Comment by soumildatta** [comment]
<img width="1680" alt="Screen Shot 2020-01-07 at 11 32 52 AM" src="https://user-images.githubusercontent.com/35431692/71916757-46961700-3144-11ea-91b0-9e56e826c93f.png">

**Grid**: Bootstrap small (col-sm) grid added
**Animations**: Tile zooms in when hovered over and zooms out (but not to original size) when clicked
